name: firstapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  linkwell: ^2.0.0
  url_launcher: ^6.1.10
  quickalert: ^1.0.1
  googleapis: 10.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  cloud_firestore: 2.5.0
  firebase_auth: 3.1.4
  provider: ^6.0.5
  firebase_core_platform_interface: 4.5.1 # note removed ^
  google_sign_in: 5.2.0
  sign_in_with_apple: 3.2.0
  crypto: 3.0.1
  font_awesome_flutter: 9.2.0
  google_fonts: ^4.0.3
  rxdart: 0.27.2
  get:
  json_annotation: ^4.6.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.9
  http: ^0.13.5

  image_picker: ^0.8.7+3
  firebase_storage: ^10.3.11
  firebase_database: ^9.1.7

  carousel_slider: ^4.2.1
  multiselect: ^0.1.0
  dynamic_color: ^1.6.3
  photo_view: ^0.14.0

  # google_auth_io: ^2.1.0
# auth: FirebaseAuthWeb.instance;
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner : ^2.2.0
  json_serializable: ^6.3.1
flutter:
  assets:

    - assets/images/download.png
    - assets/images/Transperant_IITI.png
    - assets/images/campus.png

    - assets/images/
#    - assets/images/download.png
#    - assets/images/Transperant_IITI.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/Roboto/Roboto-Regular.ttf
        - asset: assets/Roboto/Roboto-Bold.ttf
          weight: 700

  uses-material-design: true

 
