// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLLPpjPapRU-hLGxwHKve0KJPROiBjgXc',
    appId: '1:710399060234:android:ab10efa5121cd56602f2f3',
    messagingSenderId: '710399060234',
    projectId: 'ashu-ab900',
    storageBucket: 'ashu-ab900.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRhypW3oC8Ij_Tnd0ie5w0kxulyHu1310',
    appId: '1:710399060234:ios:57219a2e345d028a02f2f3',
    messagingSenderId: '710399060234',
    projectId: 'ashu-ab900',
    storageBucket: 'ashu-ab900.appspot.com',
    androidClientId: '710399060234-goduuvh2htd6pomkdpaa1d7cbqa0htn0.apps.googleusercontent.com',
    iosClientId: '710399060234-pp8npr5vbfm3depua0qsve9mc4oif0si.apps.googleusercontent.com',
    iosBundleId: 'asm.ashutosh.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRhypW3oC8Ij_Tnd0ie5w0kxulyHu1310',
    appId: '1:710399060234:ios:57219a2e345d028a02f2f3',
    messagingSenderId: '710399060234',
    projectId: 'ashu-ab900',
    storageBucket: 'ashu-ab900.appspot.com',
    androidClientId: '710399060234-goduuvh2htd6pomkdpaa1d7cbqa0htn0.apps.googleusercontent.com',
    iosClientId: '710399060234-pp8npr5vbfm3depua0qsve9mc4oif0si.apps.googleusercontent.com',
    iosBundleId: 'asm.ashutosh.firstapp',
  );
}
